//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class daysForAVolunteer
    {
        public int daysForAVolunteerCode { get; set; }
        public int dayInTheWeek { get; set; }
        public int beginningTime { get; set; }
        public int endTime { get; set; }
        public int VolunteerOffersCode { get; set; }
    
        public virtual VolunteerOffer VolunteerOffer { get; set; }
    }
}
