//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VolunteerPlacementSystemDBEntities1 : DbContext
    {
        public VolunteerPlacementSystemDBEntities1()
            : base("name=VolunteerPlacementSystemDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<daysForAVolunteer> daysForAVolunteers { get; set; }
        public virtual DbSet<embeddedVolunteer> embeddedVolunteers { get; set; }
        public virtual DbSet<roleForVolunteer> roleForVolunteers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<VolunteerHoursByWard> VolunteerHoursByWards { get; set; }
        public virtual DbSet<volunteeringForWard> volunteeringForWards { get; set; }
        public virtual DbSet<VolunteerOffer> VolunteerOffers { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<wardDirector> wardDirectors { get; set; }
        public virtual DbSet<ward> wards { get; set; }
    }
}
