//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VolunteerOffer()
        {
            this.daysForAVolunteers = new HashSet<daysForAVolunteer>();
        }
    
        public int VolunteerOffersCode { get; set; }
        public int VolunteerCode { get; set; }
        public int TotalNumberOfHoursPerWeek { get; set; }
        public bool flexible { get; set; }
        public System.DateTime offersDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daysForAVolunteer> daysForAVolunteers { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
