//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volunteer()
        {
            this.embeddedVolunteers = new HashSet<embeddedVolunteer>();
            this.roleForVolunteers = new HashSet<roleForVolunteer>();
            this.VolunteerOffers = new HashSet<VolunteerOffer>();
        }
    
        public int VolunteerCode { get; set; }
        public string VolunteerID { get; set; }
        public string VolunteerFirstName { get; set; }
        public string VolunteerLastName { get; set; }
        public System.DateTime VolunteerDateOfBirth { get; set; }
        public string VolunteerPhone { get; set; }
        public string VolunteerAddress { get; set; }
        public string VolunteerGmail { get; set; }
        public string VolunteerPassword { get; set; }
        public string volunteerUsername { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<embeddedVolunteer> embeddedVolunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roleForVolunteer> roleForVolunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerOffer> VolunteerOffers { get; set; }
    }
}
