//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wardDirector
    {
        public int wardDirectorCode { get; set; }
        public string wardDirectorID { get; set; }
        public string wardDirectorFirstName { get; set; }
        public string wardDirectorLastName { get; set; }
        public string wardDirectorPassword { get; set; }
        public string wardDirectorUsername { get; set; }
        public int wardCode { get; set; }
    
        public virtual ward ward { get; set; }
    }
}
